### PR TITLE
re-adding draft pull request

### PR DESCRIPTION
**Pull request by mylescorrea**
Resubmitted draft pull request

### CODE REVIEW

**Comment by rkarmuri** [comment]
Good use of the sub-components. The web API is not functional. I ran into errors while running the Flask app. Fix, the errors you are encountering, and work with your teammates to connect the client to the server.

**Review by rkarmuri — DISMISSED** [review]
There are some bugs in app.py when establishing the connection. I made changes to it, and now it looks good. We are not using the scantron.py file yet, but we are trying to follow the pattern in the book "Clean architectures in Python".

**Review by rkarmuri — DISMISSED** [review]
There are some bugs in app.py when establishing the connection. I made changes to it, and now it looks good. We are not using the scantron.py file yet, but we are trying to follow the pattern in the book "Clean Architectures in Python".

**Review by mylescorrea — COMMENTED** [review]
fixed app.py bugs

**Pull request closed without merging**
